"""empty message

Revision ID: 08764d035684
Revises: 
Create Date: 2021-05-24 15:23:01.586284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08764d035684'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BranchDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=50), nullable=False),
    sa.Column('branch_address', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FundTransfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_account', sa.String(length=8), nullable=False),
    sa.Column('to_account', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TokenBlockList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TransactionType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('email_id', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_type_id'], ['UserType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_table('BankAccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('account_balance', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_type_id'], ['AccountType.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['BranchDetails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('AccountTransactionDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('transaction_status', sa.String(length=50), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('fund_transfer_id', sa.Integer(), nullable=False),
    sa.Column('fund_transfer_info', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['BankAccount.id'], ),
    sa.ForeignKeyConstraint(['fund_transfer_id'], ['FundTransfer.id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['TransactionType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AccountTransactionDetails')
    op.drop_table('BankAccount')
    op.drop_table('User')
    op.drop_table('UserType')
    op.drop_table('TransactionType')
    op.drop_table('TokenBlockList')
    op.drop_table('FundTransfer')
    op.drop_table('BranchDetails')
    op.drop_table('AccountType')
    # ### end Alembic commands ###
