"""empty message

Revision ID: 49c08f76fbbb
Revises: d4c15f7eb04b
Create Date: 2021-05-27 13:37:26.163070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49c08f76fbbb'
down_revision = 'd4c15f7eb04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'aadhar_card_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('aadhar_card_no', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
